version: '3'

networks:
  file-upload-app:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - file-upload-app


  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php
    volumes:
      - .:/var/www/
    ports:
      - "9000:9000"
    networks:
      - file-upload-app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    depends_on:
      - php
    networks:
      - file-upload-app

  artisan:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: artisan
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - file-upload-app

volumes:
  dbdata:
    driver: local